// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SimpleMenuPlugin","status":true,"description":"Simple Menu Plugin v1.0.0","parameters":{"hideCharacterProfiles":"true\r\n\r\nThis plugin simplifies the menu system by:\r\n- Removing weapons and armor from inventory (only items and key items remain)\r\n- Removing Skills, Equip, and Formation from the main menu\r\n- Optionally hiding character profiles on the left side\r\n\r\nIt does not provide plugin commands."}}
];
